### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by i4lina** [emilio-toledo/obsidian-svelte-plugin#1]
Hi, first of all, I wanted to thank you because I've been trying to get Tailwind up and running for a day and I couldn't. I'm opening this issue because hot reloading and reloading in general don't seem to work.
Any edit in the Svelte files causes the plugin to rebuild (I can see it from the logs), but then nothing happens in the Obsidian app. I've tried manually refreshing the plugins, but nothing happens. If I close the app and open it again, the changes are present. What could it be? From adding a debug statement to the hot reload code, it appears that the function that handles file changes does not fire. Perhaps it does not register the file changes?

**Comment by emilio-toledo** [comment]
Hey @i4lina, that is extremely weird. Let me get home an I will look into it. In the meantime do you mind telling me the contents of your `test-vault/.obsidian/plugins/obsidian-svelte-plugin`?

**Comment by i4lina** [comment]
Thanks for getting back to me. In the folder I have the minified main.js, manifest.json, styles.css with tailwind classes and versions.json

I've changed the plugin name in the file system (plugin dir), in the manifest and in the vite config. Maybe that could be the problem? I will try cloning the original repo again and see if the problem persists

**Comment by i4lina** [comment]
I've created a new plugin and only changed the content of the svelte file but the problem persists

**Comment by emilio-toledo** [comment]
No problem. There should be a `.hotreload` file inside `test-vault/.obsidian/plugins/obsidian-svelte-plugin` for the hot-reload plugin to watch for changes. If there is no `.hotreload` can you create it and tell me if it works? Maybe somewhere in the process of copying the files into the test-vault the `.hotreload` is being deleted.

**Comment by i4lina** [comment]
Apparently in the fresh plugin the .hotreload is present, in mine is missing cause I've changed the vite outdir, so it has generated the new files but I didn't manually add the .hotreload.

So the hotreload plugin should reload our plugin and it doesn't. 
I think the problem is somewhere else cause manually refreshing third party plugins from the obsidian settings doesn't refresh the plugin either. I don't know where else to look for the problem, I'm quite new to obsidian

**Comment by emilio-toledo** [comment]
To what did you change the Vite out dir?

**Comment by i4lina** [comment]
```
const setOutDir = (mode: string) => {
  switch (mode) {
    case "development":
      return "./test-vault/.obsidian/plugins/cute-flashcards";
    case "production":
      return "build";
  }
};
```
This matches the name of the plugin in the manifest.json

**Comment by emilio-toledo** [comment]
@i4lina sorry for the late response. I have not managed to reproduce the behavior you are getting as I can reload manually and use the auto reload functionality. Can you try just clean fetching the template once again without modifying anything aside from the Example.svelte to see if it works? Maybe it has something to do with the installation of obsidian that you have, but without any further context I cant really see how to help :/
