### ISSUE TITLE
Sourcemapping?

### ISSUE THREAD

**Issue by martinjo** [emilio-toledo/obsidian-svelte-plugin#2]
Thanks for the great template, it really sped up my plugin dev. 

I can't seem to figure out if or how source mapping works. When debugging I only see the JavaScript code no matter what I do. Is the template configured for source mapping to work, it is there any way to enable it?

**Comment by emilio-toledo** [comment]
Hey @martinjo I am happy to hear that you find my template useful!

To be honest it's my first time hearing about source mapping but after doing some digging I found a [vite source map setting](https://vitejs.dev/config/build-options.html#build-sourcemap). Let me know if this is what you are looking for :) 

Edit 1: Doing some more research, I found that typescript also offers a [sourceMap](https://www.typescriptlang.org/tsconfig#sourceMap) setting so just add it to the tsconfig file and together with vite's source map setting everything should work correctly. 

Edit 2: Now that I understand what source maps are and notice their potential usefulness, I should add them to the template or if you want you can create a PR with these changes and if they work for you I will merge them.

**Comment by emilio-toledo** [comment]
Also @martinjo I am pretty new to obsidian plugin development so if there are any repetitive examples or common patterns that arise when developing plugins please let me know so that I can add them to the template.

**Comment by martinjo** [comment]
Thanks! I tried that option and it seems to work now. 

I hade to set an additional option to get the debugger to actually find the .map file:
**output.sourcemapBaseUrl**

I added added my plugin dir under the "Filesystem" tab in the debugger. Right-clicking the .map file there gave me an option to "Copy link-address" and then I took the base adress from there and set my sourceBaseUrl to that.

rollupOptions: {
		output: {
			entryFileNames: "main.js",
			assetFileNames: "styles.css",
			sourcemapBaseUrl: 'file:/// ...my local vault path...  /.obsidian/plugins/obsidian-svelte-plugin/'
		},

**Comment by emilio-toledo** [comment]
Nice! @martinjo I'm happy to hear that you figured it out, do you mind creating the pr with those changes?

**Comment by martinjo** [comment]
I'm not sure how to set sourcemapBaseUrl to a relative path. But I guess we can set the sourcemap option for vite and write an instruction on how to set soucemapBaseUrl...

**Comment by emilio-toledo** [comment]
@martinjo since you are adding the changes into `vite.config.ts` maybe you can resolve the path using something like path.resolve or other path methods to convert it into an absolute one

**Comment by martinjo** [comment]
That's a much better way to do it if possible :) but I don't have time to try it now. I guess a new PR with that change would be easy to make later...

**Comment by emilio-toledo** [comment]
All right, I will merge your pr and we can later try the path resolve method

**Comment by emilio-toledo** [comment]
Resolved in: c4cecb9
